### utility
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'tpope/vim-commentary'
on_map = ['gc', 'gcc']

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeShowHidden = 1
'''
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
depends = 'nerdtree'
on_cmd = ['NERDTreeTabs', 'NERDTreeTabsToggle', 'NERDTreeTabsFind']
hook_add = '''
    nnoremap <silent><C-n> :NERDTreeTabsToggle<CR>
'''
hook_post_source = '''
    map <leader>r :NERDTreeTabsFind<CR>
    autocmd BufEnter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
'''

[[plugins]]
repo = 'junegunn/fzf'
hook_post_update = './install --all'
merged = 0

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
on_cmd = [
    'Rg',
    'Files',
    'History'
]
hook_add = '''
    command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \ 'rg --column --line-number --hidden --ignore-case --no-heading --color=always '.shellescape(<q-args>), 1,
    \ <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
    \ : fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'right:50%:hidden', '?'),
    \ <bang>0)

    nnoremap <C-g> :Rg<Space>
    nnoremap <C-f> :Files<CR>
    nnoremap <C-p> :History<CR>
'''

