[[plugins]]
repo = 'Shougo/dein.vim'

### theme
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
    set background=dark
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    set laststatus=2
    let g:airline_theme = 'iceberg'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

### utility
[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


### completion
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    " let g:lsp_diagnostics_echo_cursor = 1
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_completion_start_length = 1
    let g:python_host_prog = '/bin/python3'
    let g:python3_host_prog = '/bin/python3'

    call deoplete#custom#option('auto_complete_delay', 150)
    call deoplete#custom#option('auto_refresh_delay', 10)
    call deoplete#custom#option('ignore_case', v:true)
    call deoplete#custom#option('smart_case', v:true)
    call deoplete#custom#option('max_list', 50)
    call deoplete#custom#option('min_pattern_length', 1)
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'


### snippets
[[plugins]]
repo = 'SirVer/ultisnips'
[[plugins]]
repo = 'honza/vim-snippets'


### git
[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

